packages: prevent nodejs script to run if mise is not installed

diff --git a/packages/nodejs b/packages/nodejs
--- a/packages/nodejs
+++ b/packages/nodejs
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if ! command -v mise > /dev/null; then
+  echo "mise is required to run this script"
+  exit 1
+fi
+
 mise install node@18 node@20
 
 # Default version
